import { Feather } from '@expo/vector-icons';
import React, { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { IconButton, Pill, PrimaryButton, SectionTitle } from '@/components/Ui';

export default function LibraryScreen() {
  const c = useColors(); const insets = useSafeAreaInsets(); const [materials, setMaterials] = useState<string[]>(['Human Anatomy — lecture 04.pdf']);
  const addMaterial = () => { setMaterials((items) => [...items, 'New lecture material.mp4']); Alert.alert('Material added', 'Ready to generate a focused five-question exam.'); };
  return <ScrollView style={{ backgroundColor: c.background }} contentContainerStyle={[styles.content, { paddingTop: insets.top + 18, paddingBottom: insets.bottom + 100 }]}><View style={styles.header}><View><Text style={[styles.eyebrow, { color: c.primary }]}>MATERIALS</Text><Text style={[styles.heading, { color: c.foreground }]}>Your study shelf</Text></View><IconButton name="search" label="Search materials" onPress={() => {}} /></View><Text style={[styles.intro, { color: c.mutedForeground }]}>Bring your own context. EduAI will turn it into a sharp practice session.</Text>
    <Pressable testID="add-material" onPress={addMaterial} style={({ pressed }) => [styles.upload, { borderColor: c.primary, backgroundColor: c.accent, opacity: pressed ? 0.72 : 1 }]}><View style={[styles.uploadIcon, { backgroundColor: c.primary }]}><Feather name="upload-cloud" size={21} color={c.primaryForeground} /></View><View style={{ flex: 1 }}><Text style={[styles.uploadTitle, { color: c.foreground }]}>Generate from materials</Text><Text style={[styles.small, { color: c.mutedForeground }]}>PDF, images, TXT, DOCX, MP4 or lecture links</Text></View><Feather name="plus" size={20} color={c.foreground} /></Pressable>
    <SectionTitle eyebrow="Saved context" title={`${materials.length} materials`} action="Manage" />{materials.map((item, index) => <View key={`${item}-${index}`} style={[styles.material, { backgroundColor: c.card, borderColor: c.border }]}><View style={[styles.fileIcon, { backgroundColor: index === 0 ? c.accent : c.secondary }]}><Feather name={index === 0 ? 'file-text' : 'video'} size={18} color={index === 0 ? c.accentForeground : c.mutedForeground} /></View><View style={{ flex: 1 }}><Text style={[styles.materialTitle, { color: c.foreground }]} numberOfLines={1}>{item}</Text><Text style={[styles.small, { color: c.mutedForeground }]}>{index === 0 ? 'PDF · 2.4 MB · parsed' : 'VIDEO · processing complete'}</Text></View><Feather name="more-horizontal" size={19} color={c.mutedForeground} /></View>)}<View style={[styles.tip, { backgroundColor: c.card }]}><Feather name="shield" size={18} color={c.primary} /><View style={{ flex: 1 }}><Text style={[styles.tipTitle, { color: c.foreground }]}>Your context stays yours</Text><Text style={[styles.small, { color: c.mutedForeground }]}>Materials are used only to build your personal practice set.</Text></View></View><PrimaryButton onPress={() => Alert.alert('Select a material', 'Choose a saved material to generate a quiz.')}>Build a quiz</PrimaryButton></ScrollView>;
}
const styles = StyleSheet.create({ content: { paddingHorizontal: 20, gap: 18 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, eyebrow: { fontFamily: 'Inter_700Bold', fontSize: 11, letterSpacing: 1.6, marginBottom: 5 }, heading: { fontFamily: 'Inter_700Bold', fontSize: 27, letterSpacing: -0.8 }, intro: { fontFamily: 'Inter_500Medium', fontSize: 14, lineHeight: 20, maxWidth: 320 }, upload: { borderRadius: 20, borderWidth: 1, borderStyle: 'dashed', padding: 15, flexDirection: 'row', alignItems: 'center', gap: 12 }, uploadIcon: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, uploadTitle: { fontFamily: 'Inter_700Bold', fontSize: 14, marginBottom: 4 }, small: { fontFamily: 'Inter_500Medium', fontSize: 12, lineHeight: 17 }, material: { borderWidth: 1, borderRadius: 18, padding: 13, flexDirection: 'row', alignItems: 'center', gap: 12 }, fileIcon: { width: 40, height: 40, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, materialTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 14, marginBottom: 4 }, tip: { padding: 16, borderRadius: 18, flexDirection: 'row', gap: 12 }, tipTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 14, marginBottom: 4 } });