import { Feather } from '@expo/vector-icons';
import React from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useApp } from '@/context/AppContext';
import { useColors } from '@/hooks/useColors';
import { Pill, SectionTitle } from '@/components/Ui';

export default function ShopScreen() {
  const c = useColors(); const insets = useSafeAreaInsets(); const { wallet, shop, buyItem, equipItem } = useApp();
  const purchase = (id: string, title: string, cost: number, owned: boolean) => { if (owned) { equipItem(id); Alert.alert('Equipped', `${title} is now active.`); } else if (wallet >= cost) { buyItem(id); Alert.alert('Unlocked', `${title} has been added to your collection.`); } else Alert.alert('Keep studying', `You need ${cost - wallet} more points to unlock this.`); };
  return <ScrollView style={{ backgroundColor: c.background }} contentContainerStyle={[styles.content, { paddingTop: insets.top + 18, paddingBottom: insets.bottom + 100 }]}><View style={styles.header}><View><Text style={[styles.eyebrow, { color: c.primary }]}>POINT SHOP</Text><Text style={[styles.heading, { color: c.foreground }]}>Make it yours</Text></View><View style={[styles.wallet, { backgroundColor: c.accent }]}><Feather name="zap" size={15} color={c.accentForeground} /><Text style={[styles.walletText, { color: c.accentForeground }]}>{wallet}</Text></View></View><Text style={[styles.intro, { color: c.mutedForeground }]}>Pass exams, collect points, and turn your study space into something personal.</Text><View style={[styles.balance, { backgroundColor: c.primary }]}><Text style={[styles.balanceLabel, { color: c.primaryForeground }]}>AVAILABLE TO SPEND</Text><Text style={[styles.balanceValue, { color: c.primaryForeground }]}>{wallet} <Text style={styles.pts}>pts</Text></Text><View style={[styles.balanceLine, { backgroundColor: c.primaryForeground }]}><View style={[styles.balanceFill, { backgroundColor: c.primaryForeground, width: `${Math.min(wallet / 50, 1) * 100}%` }]} /></View></View><SectionTitle eyebrow="The collection" title="Small upgrades, big energy" />{shop.map((item) => <Pressable key={item.id} onPress={() => purchase(item.id, item.title, item.cost, item.owned)} style={({ pressed }) => [styles.item, { backgroundColor: c.card, borderColor: item.equipped ? c.primary : c.border, opacity: pressed ? 0.74 : 1 }]}><View style={[styles.itemIcon, { backgroundColor: item.equipped ? c.primary : c.secondary }]}><Feather name={item.icon as keyof typeof Feather.glyphMap} size={19} color={item.equipped ? c.primaryForeground : c.foreground} /></View><View style={{ flex: 1 }}><Text style={[styles.itemTitle, { color: c.foreground }]}>{item.title}</Text><Text style={[styles.small, { color: c.mutedForeground }]}>{item.subtitle}</Text></View>{item.equipped ? <Pill>Equipped</Pill> : item.owned ? <Pill>Equip</Pill> : <View style={styles.price}><Feather name="zap" size={12} color={c.primary} /><Text style={[styles.priceText, { color: c.foreground }]}>{item.cost}</Text></View>}</Pressable>)}</ScrollView>;
}
const styles = StyleSheet.create({ content: { paddingHorizontal: 20, gap: 18 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, eyebrow: { fontFamily: 'Inter_700Bold', fontSize: 11, letterSpacing: 1.6, marginBottom: 5 }, heading: { fontFamily: 'Inter_700Bold', fontSize: 27, letterSpacing: -0.8 }, intro: { fontFamily: 'Inter_500Medium', fontSize: 14, lineHeight: 20, maxWidth: 330 }, wallet: { borderRadius: 18, paddingHorizontal: 12, paddingVertical: 9, flexDirection: 'row', gap: 6, alignItems: 'center' }, walletText: { fontFamily: 'Inter_700Bold', fontSize: 15 }, balance: { borderRadius: 22, padding: 19 }, balanceLabel: { fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 1.3, opacity: 0.8 }, balanceValue: { fontFamily: 'Inter_700Bold', fontSize: 37, marginTop: 4 }, pts: { fontFamily: 'Inter_500Medium', fontSize: 14 }, balanceLine: { height: 5, borderRadius: 3, opacity: 0.2, marginTop: 16 }, balanceFill: { height: '100%', borderRadius: 3, opacity: 1 }, item: { borderRadius: 18, borderWidth: 1, padding: 13, flexDirection: 'row', alignItems: 'center', gap: 12 }, itemIcon: { width: 43, height: 43, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, itemTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 14, marginBottom: 4 }, small: { fontFamily: 'Inter_500Medium', fontSize: 12, lineHeight: 17 }, price: { flexDirection: 'row', alignItems: 'center', gap: 4 }, priceText: { fontFamily: 'Inter_700Bold', fontSize: 14 } });