import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Level, useApp } from '@/context/AppContext';
import { useColors } from '@/hooks/useColors';
import { IconButton, PrimaryButton } from '@/components/Ui';
const levels: { group: string; items: Level[] }[] = [{ group: 'High school', items: ['Liceo Scientifico', 'Liceo Classico', 'Istituto Tecnico'] }, { group: 'University', items: ['Medicine', 'Engineering', 'Law', 'Economics'] }];
export default function OnboardingScreen() { const c = useColors(); const insets = useSafeAreaInsets(); const { level, completeOnboarding } = useApp(); const [selected, setSelected] = useState<Level>(level); return <ScrollView style={{ backgroundColor: c.background }} contentContainerStyle={[styles.content, { paddingTop: insets.top + 18, paddingBottom: insets.bottom + 28 }]}><IconButton name="x" label="Close onboarding" onPress={() => router.back()} /><Text style={[styles.kicker, { color: c.primary }]}>CALIBRATE YOUR AI</Text><Text style={[styles.heading, { color: c.foreground }]}>Where are you in your learning journey?</Text><Text style={[styles.body, { color: c.mutedForeground }]}>Your track shapes the difficulty, language, and depth of every question EduAI creates for you.</Text>{levels.map((group) => <View key={group.group} style={styles.group}><Text style={[styles.groupTitle, { color: c.mutedForeground }]}>{group.group}</Text>{group.items.map((item) => <Pressable key={item} onPress={() => setSelected(item)} style={({ pressed }) => [styles.option, { backgroundColor: selected === item ? c.accent : c.card, borderColor: selected === item ? c.primary : c.border, opacity: pressed ? 0.75 : 1 }]}><Text style={[styles.optionText, { color: c.foreground }]}>{item}</Text><View style={[styles.radio, { borderColor: selected === item ? c.primary : c.mutedForeground, backgroundColor: selected === item ? c.primary : 'transparent' }]}>{selected === item ? <Feather name="check" size={13} color={c.primaryForeground} /> : null}</View></Pressable>)}</View>)}<PrimaryButton onPress={() => { completeOnboarding(selected); router.back(); }}>Save my study track</PrimaryButton></ScrollView>; }
const styles = StyleSheet.create({ content: { paddingHorizontal: 20, gap: 16 }, kicker: { fontFamily: 'Inter_700Bold', fontSize: 11, letterSpacing: 1.6, marginTop: 20 }, heading: { fontFamily: 'Inter_700Bold', fontSize: 30, lineHeight: 36, letterSpacing: -0.9, maxWidth: 350 }, body: { fontFamily: 'Inter_500Medium', fontSize: 15, lineHeight: 22 }, group: { gap: 9, marginTop: 7 }, groupTitle: { fontFamily: 'Inter_700Bold', textTransform: 'uppercase', letterSpacing: 1.2, fontSize: 10 }, option: { borderWidth: 1, borderRadius: 16, padding: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, optionText: { fontFamily: 'Inter_600SemiBold', fontSize: 15 }, radio: { width: 24, height: 24, borderRadius: 12, borderWidth: 1, alignItems: 'center', justifyContent: 'center' } });